In [63]:
!pip install -r ../requirements.txt
print("··· Instalación en el entorno finalizada ···")

Requirement already satisfied: pandas in c:\users\usuario\documents\master\proyecto_1\.venv\lib\site-packages (from -r ../requirements.txt (line 1)) (2.3.3)
Requirement already satisfied: numpy in c:\users\usuario\documents\master\proyecto_1\.venv\lib\site-packages (from -r ../requirements.txt (line 2)) (2.3.5)
Requirement already satisfied: matplotlib in c:\users\usuario\documents\master\proyecto_1\.venv\lib\site-packages (from -r ../requirements.txt (line 3)) (3.10.7)
Requirement already satisfied: seaborn in c:\users\usuario\documents\master\proyecto_1\.venv\lib\site-packages (from -r ../requirements.txt (line 4)) (0.13.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\usuario\documents\master\proyecto_1\.venv\lib\site-packages (from pandas->-r ../requirements.txt (line 1)) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\usuario\documents\master\proyecto_1\.venv\lib\site-packages (from pandas->-r ../requirements.txt (line 1)) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\usuario\documents\master\proyecto_1\.venv\lib\site-packages (from pandas->-r ../requirements.txt (line 1)) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\usuario\documents\master\proyecto_1\.venv\lib\site-packages (from matplotlib->-r ../requirements.txt (line 3)) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\usuario\documents\master\proyecto_1\.venv\lib\site-packages (from matplotlib->-r ../requirements.txt (line 3)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\usuario\documents\master\proyecto_1\.venv\lib\site-packages (from matplotlib->-r ../requirements.txt (line 3)) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\usuario\documents\master\proyecto_1\.venv\lib\site-packages (from matplotlib->-r ../requirements.txt (line 3)) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\usuario\documents\master\proyecto_1\.venv\lib\site-packages (from matplotlib->-r ../requirements.txt (line 3)) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\usuario\documents\master\proyecto_1\.venv\lib\site-packages (from matplotlib->-r ../requirements.txt (line 3)) (12.0.0)
Requirement already satisfied: pyparsing>=3 in c:\users\usuario\documents\master\proyecto_1\.venv\lib\site-packages (from matplotlib->-r ../requirements.txt (line 3)) (3.2.5)
Requirement already satisfied: six>=1.5 in c:\users\usuario\documents\master\proyecto_1\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas->-r ../requirements.txt (line 1)) (1.17.0)
··· Instalación en el entorno finalizada ···

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [64]:
import pandas as pd
import numpy as np
import os

In [65]:
files = {
    "df2015": "../data/2015.csv",
    "df2016": "../data/2016.csv",
    "df2017": "../data/2017.csv",
    "df2018": "../data/2018.csv",
    "df2019": "../data/2019.csv"
}

datasets = {}

for name, path in files.items():
    try:
        df = pd.read_csv(path, sep=",")
        datasets[name] = df
        print(f"{name} cargado correctamente ({len(df)} filas).")
    except Exception as e:
        print(f"Ha habido un error al cargar los datasets: {e}")

df2015 cargado correctamente (158 filas).
df2016 cargado correctamente (157 filas).
df2017 cargado correctamente (155 filas).
df2018 cargado correctamente (156 filas).
df2019 cargado correctamente (156 filas).

Observemos los primeros datos del dataset con el año más viejo para comprarlos con el año más actual

In [66]:
datasets["df2015"].head()

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738
1,Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201
2,Denmark,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204
3,Norway,Western Europe,4,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531
4,Canada,North America,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176

In [67]:
datasets["df2019"].head()

,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Finland,7.769,1.340,1.587,0.986,0.596,0.153,0.393
1,2,Denmark,7.600,1.383,1.573,0.996,0.592,0.252,0.410
2,3,Norway,7.554,1.488,1.582,1.028,0.603,0.271,0.341
3,4,Iceland,7.494,1.380,1.624,1.026,0.591,0.354,0.118
4,5,Netherlands,7.488,1.396,1.522,0.999,0.557,0.322,0.298

In [68]:
datasets["df2015"].info()
# 158 filas y 12 columnas, ningún nulo

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 158 entries, 0 to 157
Data columns (total 12 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Country                        158 non-null    object
 1   Region                         158 non-null    object
 2   Happiness Rank                 158 non-null    int64
 3   Happiness Score                158 non-null    float64
 4   Standard Error                 158 non-null    float64
 5   Economy (GDP per Capita)       158 non-null    float64
 6   Family                         158 non-null    float64
 7   Health (Life Expectancy)       158 non-null    float64
 8   Freedom                        158 non-null    float64
 9   Trust (Government Corruption)  158 non-null    float64
 10  Generosity                     158 non-null    float64
 11  Dystopia Residual              158 non-null    float64
dtypes: float64(9), int64(1), object(2)
memory usage: 14.9+ KB

In [69]:
datasets["df2016"].info()
# 157 filas y 13 columnas, ningún nulo

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 13 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Country                        157 non-null    object
 1   Region                         157 non-null    object
 2   Happiness Rank                 157 non-null    int64
 3   Happiness Score                157 non-null    float64
 4   Lower Confidence Interval      157 non-null    float64
 5   Upper Confidence Interval      157 non-null    float64
 6   Economy (GDP per Capita)       157 non-null    float64
 7   Family                         157 non-null    float64
 8   Health (Life Expectancy)       157 non-null    float64
 9   Freedom                        157 non-null    float64
 10  Trust (Government Corruption)  157 non-null    float64
 11  Generosity                     157 non-null    float64
 12  Dystopia Residual              157 non-null    float64
dtypes: float64(10), int64(1), object(2)
memory usage: 16.1+ KB

In [70]:
datasets["df2017"].info()
# 155 filas y 12 columnas, ningún nulo

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 155 entries, 0 to 154
Data columns (total 12 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Country                        155 non-null    object
 1   Happiness.Rank                 155 non-null    int64
 2   Happiness.Score                155 non-null    float64
 3   Whisker.high                   155 non-null    float64
 4   Whisker.low                    155 non-null    float64
 5   Economy..GDP.per.Capita.       155 non-null    float64
 6   Family                         155 non-null    float64
 7   Health..Life.Expectancy.       155 non-null    float64
 8   Freedom                        155 non-null    float64
 9   Generosity                     155 non-null    float64
 10  Trust..Government.Corruption.  155 non-null    float64
 11  Dystopia.Residual              155 non-null    float64
dtypes: float64(10), int64(1), object(1)
memory usage: 14.7+ KB

In [71]:
datasets["df2018"].info()
# 156 filas y 9 columnas, un solo nulo

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 9 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Overall rank                  156 non-null    int64
 1   Country or region             156 non-null    object
 2   Score                         156 non-null    float64
 3   GDP per capita                156 non-null    float64
 4   Social support                156 non-null    float64
 5   Healthy life expectancy       156 non-null    float64
 6   Freedom to make life choices  156 non-null    float64
 7   Generosity                    156 non-null    float64
 8   Perceptions of corruption     155 non-null    float64
dtypes: float64(7), int64(1), object(1)
memory usage: 11.1+ KB

In [72]:
datasets["df2019"].info()
# 156 filas y 9 columnas, ningún nulo

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 9 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Overall rank                  156 non-null    int64
 1   Country or region             156 non-null    object
 2   Score                         156 non-null    float64
 3   GDP per capita                156 non-null    float64
 4   Social support                156 non-null    float64
 5   Healthy life expectancy       156 non-null    float64
 6   Freedom to make life choices  156 non-null    float64
 7   Generosity                    156 non-null    float64
 8   Perceptions of corruption     156 non-null    float64
dtypes: float64(7), int64(1), object(1)
memory usage: 11.1+ KB

Podemos comprobar que los datasets son bastante parecidos, tienen ligeras diferencias como la sintaxis del nombre de las columnas (Trust (Government Corruption) - Trust..Government.Corruption.) y que los datasets más actuales, 2018 y 2019 tienen menos columnas que años anteriores. Vamos comprobar si los tipos en las columnas siguen siendo iguales o han podido cambiar con el paso de los años.

In [73]:
print("TIPOS DE DATOS DEL DATASET 2015")
print(datasets["df2015"].dtypes)
print("--------------------------------")
print("TIPOS DE DATOS DEL DATASET 2016")
print(datasets["df2016"].dtypes)
print("--------------------------------")
print("TIPOS DE DATOS DEL DATASET 2017")
print(datasets["df2017"].dtypes)
print("--------------------------------")
print("TIPOS DE DATOS DEL DATASET 2018")
print(datasets["df2018"].dtypes)
print("--------------------------------")
print("TIPOS DE DATOS DEL DATASET 2019")
print(datasets["df2019"].dtypes)
print("--------------------------------")

TIPOS DE DATOS DEL DATASET 2015
Country                           object
Region                            object
Happiness Rank                     int64
Happiness Score                  float64
Standard Error                   float64
Economy (GDP per Capita)         float64
Family                           float64
Health (Life Expectancy)         float64
Freedom                          float64
Trust (Government Corruption)    float64
Generosity                       float64
Dystopia Residual                float64
dtype: object
--------------------------------
TIPOS DE DATOS DEL DATASET 2016
Country                           object
Region                            object
Happiness Rank                     int64
Happiness Score                  float64
Lower Confidence Interval        float64
Upper Confidence Interval        float64
Economy (GDP per Capita)         float64
Family                           float64
Health (Life Expectancy)         float64
Freedom                          float64
Trust (Government Corruption)    float64
Generosity                       float64
Dystopia Residual                float64
dtype: object
--------------------------------
TIPOS DE DATOS DEL DATASET 2017
Country                           object
Happiness.Rank                     int64
Happiness.Score                  float64
Whisker.high                     float64
Whisker.low                      float64
Economy..GDP.per.Capita.         float64
Family                           float64
Health..Life.Expectancy.         float64
Freedom                          float64
Generosity                       float64
Trust..Government.Corruption.    float64
Dystopia.Residual                float64
dtype: object
--------------------------------
TIPOS DE DATOS DEL DATASET 2018
Overall rank                      int64
Country or region                object
Score                           float64
GDP per capita                  float64
Social support                  float64
Healthy life expectancy         float64
Freedom to make life choices    float64
Generosity                      float64
Perceptions of corruption       float64
dtype: object
--------------------------------
TIPOS DE DATOS DEL DATASET 2019
Overall rank                      int64
Country or region                object
Score                           float64
GDP per capita                  float64
Social support                  float64
Healthy life expectancy         float64
Freedom to make life choices    float64
Generosity                      float64
Perceptions of corruption       float64
dtype: object
--------------------------------

Vamos primero a renombrar las columnas para poder tratar mejor la información en su colectivo

In [74]:
# 2015
datasets["df2015"] = datasets["df2015"].rename(columns={
    'Happiness Rank': 'Overall Rank', 
    'Happiness Score': 'Score', 
    'Economy (GDP per Capita)': 'GDP per Capita', 
    'Health (Life Expectancy)': 'Healthy Life Expectancy',
    'Trust (Government Corruption)': 'Perceptions of Corruption',
    'Freedom': 'Freedom to Make Life Choices',
    'Family': 'Social Support'
    })

In [75]:
# 2016
datasets["df2016"] = datasets["df2016"].rename(columns={
    'Happiness Rank': 'Overall Rank', 
    'Happiness Score': 'Score', 
    'Economy (GDP per Capita)': 'GDP per Capita', 
    'Health (Life Expectancy)': 'Healthy Life Expectancy',
    'Trust (Government Corruption)': 'Perceptions of Corruption',
    'Freedom': 'Freedom to Make Life Choices',
    'Family': 'Social Support'
    })

In [76]:
# 2017
datasets["df2017"] = datasets["df2017"].rename(columns={
    'Country': 'Country or region',
    'Happiness.Rank': 'Overall Rank',
    'Happiness.Score': 'Score', 
    'Economy..GDP.per.Capita.': 'GDP per Capita', 
    'Health..Life.Expectancy.': 'Healthy Life Expectancy',
    'Trust..Government.Corruption.': 'Perceptions of Corruption',
    'Freedom': 'Freedom to Make Life Choices',
    'Family': 'Social Support'
    })

En el dataset del 2015 se ha detectado un campo que el resto de datasets no tiene, el error estandard, vamos a comprobar la proporción del error respecto a la media para saber si podemos eliminar este campo

In [77]:
media = datasets["df2015"]['Score'].mean()
error_estandar = datasets["df2015"]['Standard Error'].max()
print(f"Proporción para: df2015: ", error_estandar / media)  

# No es una proporción significativa, así que este campo lo eliminaremos del único dataset que lo tiene para homogenizar los datos

Proporción para: df2015:  0.025471869606271035

Comprobamos si hay duplicados en los datasets

In [78]:
for name, df in datasets.items():
    print(f"Duplicados en {name}:")
    print(datasets[name].duplicated().any())
    print('-' * 40)

Duplicados en df2015:
False
----------------------------------------
Duplicados en df2016:
False
----------------------------------------
Duplicados en df2017:
False
----------------------------------------
Duplicados en df2018:
False
----------------------------------------
Duplicados en df2019:
False
----------------------------------------

Antes de comenzar con la homogeneidad de columnas, vamos a comprobar si el campo region puede fusionarse con el campo country, ya que en los datasets más actuales, este campo consta como country or region

In [79]:
# A simple vista no parece que estos dataset tenga regiones, úncamente países así que la columna Country no la vamos a fusionar con region
paises_con_espacio = datasets["df2017"][datasets["df2017"]['Country or region'].str.contains(' ', na=False)]['Country or region'].unique()
print(paises_con_espacio)

paises_con_espacio = datasets["df2018"][datasets["df2018"]['Country or region'].str.contains(' ', na=False)]['Country or region'].unique()
print(paises_con_espacio)

paises_con_espacio = datasets["df2019"][datasets["df2019"]['Country or region'].str.contains(' ', na=False)]['Country or region'].unique()
print(paises_con_espacio)

['New Zealand' 'Costa Rica' 'United States' 'United Kingdom'
 'United Arab Emirates' 'Czech Republic' 'Taiwan Province of China'
 'Saudi Arabia' 'Trinidad and Tobago' 'El Salvador' 'South Korea'
 'North Cyprus' 'Hong Kong S.A.R., China' 'Dominican Republic'
 'Bosnia and Herzegovina' 'South Africa' 'Palestinian Territories'
 'Sierra Leone' 'Sri Lanka' 'Congo (Brazzaville)' 'Congo (Kinshasa)'
 'Ivory Coast' 'Burkina Faso' 'South Sudan' 'Central African Republic']
['New Zealand' 'United Kingdom' 'Costa Rica' 'United States'
 'United Arab Emirates' 'Czech Republic' 'Saudi Arabia'
 'Trinidad & Tobago' 'El Salvador' 'South Korea' 'Northern Cyprus'
 'Hong Kong' 'Dominican Republic' 'Bosnia and Herzegovina'
 'Palestinian Territories' 'South Africa' 'Ivory Coast' 'Sierra Leone'
 'Congo (Brazzaville)' 'Sri Lanka' 'Burkina Faso' 'Congo (Kinshasa)'
 'South Sudan' 'Central African Republic']
['New Zealand' 'Costa Rica' 'United Kingdom' 'United States'
 'Czech Republic' 'United Arab Emirates' 'Saudi Arabia' 'El Salvador'
 'Trinidad & Tobago' 'South Korea' 'Northern Cyprus' 'Hong Kong'
 'Dominican Republic' 'Bosnia and Herzegovina' 'North Macedonia'
 'Ivory Coast' 'Congo (Brazzaville)' 'South Africa'
 'Palestinian Territories' 'Burkina Faso' 'Congo (Kinshasa)'
 'Sierra Leone' 'Sri Lanka' 'Central African Republic' 'South Sudan']

In [80]:
# LIMPIEZA DE DATOS PARA EL 2015
datasets["df2015"] = datasets["df2015"].rename(columns={'Country': 'Country or region'})
datasets["df2015"].insert(0, "Overall Rank", datasets["df2015"].pop("Overall Rank"))
datasets["df2015"] = datasets["df2015"].drop(columns=["Region", "Dystopia Residual", "Standard Error"])
datasets["df2015"].head()

,Overall Rank,Country or region,Score,GDP per Capita,Social Support,Healthy Life Expectancy,Freedom to Make Life Choices,Perceptions of Corruption,Generosity
0,1,Switzerland,7.587,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678
1,2,Iceland,7.561,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630
2,3,Denmark,7.527,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139
3,4,Norway,7.522,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699
4,5,Canada,7.427,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811

In [81]:
# LIMPIEZA DE DATOS PARA EL 2016
datasets["df2016"] = datasets["df2016"].rename(columns={'Country': 'Country or region'})
datasets["df2016"].insert(0, "Overall Rank", datasets["df2016"].pop("Overall Rank"))
datasets["df2016"] = datasets["df2016"].drop(columns=["Region", "Dystopia Residual", "Lower Confidence Interval", "Upper Confidence Interval"])
datasets["df2016"].head()

,Overall Rank,Country or region,Score,GDP per Capita,Social Support,Healthy Life Expectancy,Freedom to Make Life Choices,Perceptions of Corruption,Generosity
0,1,Denmark,7.526,1.44178,1.16374,0.79504,0.57941,0.44453,0.36171
1,2,Switzerland,7.509,1.52733,1.14524,0.86303,0.58557,0.41203,0.28083
2,3,Iceland,7.501,1.42666,1.18326,0.86733,0.56624,0.14975,0.47678
3,4,Norway,7.498,1.57744,1.12690,0.79579,0.59609,0.35776,0.37895
4,5,Finland,7.413,1.40598,1.13464,0.81091,0.57104,0.41004,0.25492

In [82]:
# LIMPIEZA DE DATOS PARA EL 2017
datasets["df2017"].insert(0, "Overall Rank", datasets["df2017"].pop("Overall Rank"))
datasets["df2017"] = datasets["df2017"].drop(columns=["Dystopia.Residual", "Whisker.high", "Whisker.low"])
datasets["df2017"].head()

,Overall Rank,Country or region,Score,GDP per Capita,Social Support,Healthy Life Expectancy,Freedom to Make Life Choices,Generosity,Perceptions of Corruption
0,1,Norway,7.537,1.616463,1.533524,0.796667,0.635423,0.362012,0.315964
1,2,Denmark,7.522,1.482383,1.551122,0.792566,0.626007,0.355280,0.400770
2,3,Iceland,7.504,1.480633,1.610574,0.833552,0.627163,0.475540,0.153527
3,4,Switzerland,7.494,1.564980,1.516912,0.858131,0.620071,0.290549,0.367007
4,5,Finland,7.469,1.443572,1.540247,0.809158,0.617951,0.245483,0.382612

Nuestros datasets ya están complemente igualados en cuestión de columnas, comprobemos una vez más los tipos, ahora se verá con más claridad

In [83]:
for name, df in datasets.items():
    print(f"Tipos de columnas en {name}:")
    print(df.dtypes)
    print('-' * 40)

Tipos de columnas en df2015:
Overall Rank                      int64
Country or region                object
Score                           float64
GDP per Capita                  float64
Social Support                  float64
Healthy Life Expectancy         float64
Freedom to Make Life Choices    float64
Perceptions of Corruption       float64
Generosity                      float64
dtype: object
----------------------------------------
Tipos de columnas en df2016:
Overall Rank                      int64
Country or region                object
Score                           float64
GDP per Capita                  float64
Social Support                  float64
Healthy Life Expectancy         float64
Freedom to Make Life Choices    float64
Perceptions of Corruption       float64
Generosity                      float64
dtype: object
----------------------------------------
Tipos de columnas en df2017:
Overall Rank                      int64
Country or region                object
Score                           float64
GDP per Capita                  float64
Social Support                  float64
Healthy Life Expectancy         float64
Freedom to Make Life Choices    float64
Generosity                      float64
Perceptions of Corruption       float64
dtype: object
----------------------------------------
Tipos de columnas en df2018:
Overall rank                      int64
Country or region                object
Score                           float64
GDP per capita                  float64
Social support                  float64
Healthy life expectancy         float64
Freedom to make life choices    float64
Generosity                      float64
Perceptions of corruption       float64
dtype: object
----------------------------------------
Tipos de columnas en df2019:
Overall rank                      int64
Country or region                object
Score                           float64
GDP per capita                  float64
Social support                  float64
Healthy life expectancy         float64
Freedom to make life choices    float64
Generosity                      float64
Perceptions of corruption       float64
dtype: object
----------------------------------------

Empezaremos ahora comprobando los datos que tenemos

In [84]:
for name, df in datasets.items():
    print(f"Comprobando valores nulos en {name}:")
    nulos_por_columna = datasets[name].isnull().sum()
    nulos_por_columna = nulos_por_columna[nulos_por_columna > 0]
    print(f"Valores nulos encontrados: {nulos_por_columna}")
    print('-' * 40)

Comprobando valores nulos en df2015:
Valores nulos encontrados: Series([], dtype: int64)
----------------------------------------
Comprobando valores nulos en df2016:
Valores nulos encontrados: Series([], dtype: int64)
----------------------------------------
Comprobando valores nulos en df2017:
Valores nulos encontrados: Series([], dtype: int64)
----------------------------------------
Comprobando valores nulos en df2018:
Valores nulos encontrados: Perceptions of corruption    1
dtype: int64
----------------------------------------
Comprobando valores nulos en df2019:
Valores nulos encontrados: Series([], dtype: int64)
----------------------------------------

In [85]:
#C Como solo tenemos un valor nulo en el dataset de 2018 vamos a echar un ojo
print("Posición: ", datasets["df2018"].isnull().stack().idxmax())
print("Fila del valor nulo: \n", datasets["df2018"].loc[19])

Posición:  (19, 'Perceptions of corruption')
Fila del valor nulo:
 Overall rank                                      20
Country or region               United Arab Emirates
Score                                          6.774
GDP per capita                                 2.096
Social support                                 0.776
Healthy life expectancy                         0.67
Freedom to make life choices                   0.284
Generosity                                     0.186
Perceptions of corruption                        NaN
Name: 19, dtype: object

In [86]:
print(datasets["df2018"].shape)
# Hay 156 registros, utilizaremos la media de la columna para poder rellenarla
print("--- Media que se utilizará: ", datasets["df2018"]["Perceptions of corruption"].mean(), " ---")
datasets["df2018"].loc[:, "Perceptions of corruption"] = datasets["df2018"]["Perceptions of corruption"].fillna(datasets["df2018"]["Perceptions of corruption"].mean())
print(datasets["df2018"].isnull().sum())

(156, 9)
--- Media que se utilizará:  0.112  ---
Overall rank                    0
Country or region               0
Score                           0
GDP per capita                  0
Social support                  0
Healthy life expectancy         0
Freedom to make life choices    0
Generosity                      0
Perceptions of corruption       0
dtype: int64

In [87]:
datasets["df2015"]['year'] = '2015'
datasets["df2016"]['year'] = '2016'
datasets["df2017"]['year'] = '2017'
datasets["df2018"]['year'] = '2018'
datasets["df2019"]['year'] = '2019'

In [88]:
carpeta = '../clean_data'
os.makedirs(carpeta, exist_ok=True)

for name, df in datasets.items():
    ruta_csv = os.path.join(carpeta, f'{name}.csv')
    if not os.path.exists(ruta_csv):
        df.to_csv(ruta_csv, index=False)
        print(f'Guardado: {ruta_csv}')
    else:
        print(f'Archivo ya existe, se omite: {ruta_csv}')

Guardado: ../clean_data\df2015.csv
Guardado: ../clean_data\df2016.csv
Guardado: ../clean_data\df2017.csv
Guardado: ../clean_data\df2018.csv
Guardado: ../clean_data\df2019.csv